basic_settings:
  site_title: Smiling Hogshead Ranch
#  favicon_image: /assets/img/favicon.png

header_settings:
  logo_image: /assets/img/brand/cropped-color_SHR_logo_blue.png
  mobile_logo_image: /assets/img/brand/cropped-color_SHR_logo_blue.png
  # Choose a color for your header [blue, dark, light].
  theme: dark
  # If the page has a featured image, it turns transparent if allow_transparent is set to "yes".
  allow_transparent: "yes"

home_settings:
  # Choose a layout for your home page:
    # landing – an example landing page made using the Argon design system
    # blog – use your blog posts as the home page
  theme: landing

blog_settings:
  # Choose a format for your blog listings:
    # basic – a simple list of posts
    # narrow – a masonary grid of posts
    # grid – a full-width square grid of posts
  theme: narrow
  # Should we display a narrow grid of other posts at the bottom of each blog post?
  read_more: "yes"

# Setup your navigation below – how to use the icons: 
  # 1. See all the icons available here https://demos.creative-tim.com/argon-design-system-pro/docs/1.0/foundation/icons.html
  # 2. Get the name of the icon e.g basket, then prefix with ni to make ni-basket. 
  # 3. Add a color of the icon - text-primary, text-success, text-info, text-danger, text-warning and text-default all work! 
menu_settings:
  menu_items:
    - title: 'Home'
      url: /
    - title: 'About'
      url: '/about'
    - title: Compost
      url: '/compost'
      icon: ni-trash-can-grid-58 text-primary
    - title: Calendar
      url: '/calendar.html'
    - title: Visit
      url: '/groups'
    - title: Make a Donation
      url: /donation
      icon: ni-present
    - title: Become a Member
      submenu_items:
      - title: Membership Policy
        url: /policy
        icon: ni-file-text text-primary
      - title: Renew your Membership
        url: /join
        icon: ni-badge-text text-primary
    - title: 'Contact'
      url: '/contact'

footer_settings:
  footer_tagline:
  mailing_address: '25-30 Skillman Avenue, Long Island City, NY 11101'

contact_settings:
  form_action: 'https://formspree.io/hello@jekyllthemes.io'
  confirmation_url: '/thanks'
  email_subject: 'Contact form submission'
  send_button_text: 'Send Message'

social_settings:
  facebook_url: 'https://www.facebook.com/SmilingHogsheadRanch'
  twitter_url: 'https://twitter.com/smilinghogshead'
  instagram_url: 'https://www.instagram.com/smilinghogsheadranch/'
  youtube_url: 'https://www.youtube.com/user/SmilingHogsheadRanch'
  #github_url: 'TODO: codebase here'

authors:
  helen:
    name: Helen
    picture: /assets/img/faces/team-1.jpg

advanced_settings:
  analytics_code: 
  header_js: 
  footer_js: 
